### ISSUE TITLE
Test Results Confusion

### ISSUE THREAD

**Issue by nonobelong** [diux-dev/imagenet18#9]
Thanks for your code, amazing job!
But Im a little bit confused on the results you obtained, please correct me if Im wrong.
To my understanding, the standard ImageNet Classification task should be testing on images whose shorter edges are 256 and center cropped to 224. However, at the last phrase of your codes you simply test it on size 288. If you evaluate your weights on 224 I guess you should expect some numbers below 93. Have you ever tried it?

**Comment by yaroslavvb** [comment]
For this code we used requirements from DAWN ImageNet [training competition](https://github.com/stanford-futuredata/dawn-bench-entries#imagenet-training) which does not require images to be center cropped at 224.

I expect lower results by taking center crop, since crop may discard important details. Here's an example from imagenet dataset, it's a broom, but if you take center crop, it becomes a stick
<img width="131" alt="screenshot 2018-09-14 08 41 48" src="https://user-images.githubusercontent.com/23068/45560483-15306400-b7fa-11e8-9e4c-6330ab76c812.png">

Using center crop, I think the 16-machine version would not reach 93% even with unlimited training time -- with current schedule it barely reaches 93% and then starts going down. It's pushing how far you can go with vanilla SGD/momentum -- most changes makes things worse. I think to get past 93% with cropping, extra tricks would be needed, like LARS.

Is "resize to 256, center crop to 224" what they used in current training record? (Imagenet in 4 minutes paper). I couldn't find description of cropping they used.

**Comment by nonobelong** [comment]
I couldn't find info if Tencent applied 224 cropping or not. The Japanese team Preferred Networks who trained imagenet in 15 mins applied single crop for validation but I don't know at what size they cropped. 

For the center crop explanation part, I don't get it. In your code you did use center crop didn't you? The different part is that you cropped images to 288(after resizing to 288*1.14), rather than 224.

**Comment by yaroslavvb** [comment]
The explanation of test image preprocessing is under section "A simple new training trick: rectangles!"
of http://www.fast.ai/2018/08/10/fastai-diu-imagenet/

**Comment by TccccD** [comment]
hello, Can you give a link to the Japanese team? @nonobelong

**Comment by nonobelong** [comment]
@TccccD I don't think they've released their training code tho.
[https://www.preferred-networks.jp/en/news/pr20171110](url)
